/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motorph.gui;

import com.motorph.model.Employee;
import com.motorph.model.LeaveRequest;
import com.motorph.model.Payroll;
import com.motorph.service.EmployeeService;
import com.motorph.service.LeaveRequestService;
import com.motorph.service.PayrollService;
import com.motorph.service.ReportService;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.List;

/**
 *
 * @author KrisChan
 */
public class EmployeeDB extends javax.swing.JFrame {
    private final String username;
    private final EmployeeService employeeService;
    private final LeaveRequestService leaveRequestService;
    private final PayrollService payrollService;
    private final ReportService reportService;
    private Employee loggedInEmployee;
    /**
     * Creates new form Employee
     */
    public EmployeeDB(String username) {
        this.username = username;
        this.employeeService = new EmployeeService();
        this.leaveRequestService = new LeaveRequestService();
        this.payrollService = new PayrollService();
        this.reportService = new ReportService();
        
        initComponents();
        loadEmployeeDetails();
        loadLeaveData();
        loadPayrollData();
        setLocationRelativeTo(null);
}

    private void loadEmployeeDetails() {
        loggedInEmployee = employeeService.getEmployeeByUsername(username);
        
        if (loggedInEmployee == null) {
            JOptionPane.showMessageDialog(this, "Error: Employee not found in the database.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        lblEmployeeId.setText(loggedInEmployee.getEmployeeId());
        lblEmployeeId1.setText(loggedInEmployee.getEmployeeId());
        lblFullName.setText(loggedInEmployee.getFullName());
        lblBirthday.setText(loggedInEmployee.getBirthday() != null ? loggedInEmployee.getBirthday().toString() : "N/A");
        lblAddress.setText(loggedInEmployee.getAddress());
        lblPhone.setText(loggedInEmployee.getPhoneNumber());
        lblStatus.setText(loggedInEmployee.getStatus());
        lblPosition.setText(loggedInEmployee.getPosition());
        lblDepartment.setText(loggedInEmployee.getDepartment());
        lblSupervisor.setText(loggedInEmployee.getSupervisor());
        lblBasicSalary.setText(String.valueOf(loggedInEmployee.getBasicSalary()));
        lblHourlyRate.setText(String.valueOf(loggedInEmployee.getHourlyRate()));
    }
    
    private void loadLeaveData() {
        if (loggedInEmployee == null) return;
        
        List<LeaveRequest> leaveRequests = leaveRequestService.getLeaveRequestsByEmployeeId(loggedInEmployee.getEmployeeId());
        String[] columnNames = {"ID", "Employee ID", "Leave Type", "Start Date", "End Date", "Status"};
        
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        for (LeaveRequest leave : leaveRequests) {
            Object[] row = {
                leave.getId(), leave.getEmployeeId(), leave.getLeaveType(),
                leave.getStartDate(), leave.getEndDate(), leave.getStatus()
            };
            model.addRow(row);
        }
        
        leaveTable.setModel(model);
    }
    
    private void loadPayrollData() {
        if (loggedInEmployee == null) return;
        
        List<Payroll> payrolls = payrollService.getPayrollsByEmployeeId(loggedInEmployee.getEmployeeId());
        String[] columnNames = {"Payroll ID", "Period Start", "Period End", "Working Hours", 
                               "SSS", "PhilHealth", "PAGIBIG", "Withholding Tax", 
                               "Rice Subsidy", "Phone Allowance", "Clothing Allowance"};
        
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
        for (Payroll payroll : payrolls) {
            Object[] row = {
                payroll.getPayrollId(), payroll.getPeriodStart(), payroll.getPeriodEnd(),
                payroll.getWorkingHours(), payroll.getSssContribution(), 
                payroll.getPhilhealthContribution(), payroll.getPagibigContribution(),
                payroll.getWithholdingTax(), payroll.getRiceSubsidy(),
                payroll.getPhoneAllowance(), payroll.getClothingAllowance()
            };
            model.addRow(row);
        }
        
        payrollTable.setModel(model);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEmpDetails = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRequestLeave = new javax.swing.JButton();
        btnPayroll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        EmpDataPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSupervisor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblHourlyRate = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblBasicSalary = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEmployeeId = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        requestLeavePanel = new javax.swing.JPanel();
        lblEmployeeId1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        comboLeaveType = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaveTable = new javax.swing.JTable();
        btnRequestLeaveProcess = new javax.swing.JButton();
        payrollPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        payrollTable = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        lblPayrollId = new javax.swing.JLabel();
        btnGeneratePayslip = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpDetails.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEmpDetails.setText("Employee Details");
        btnEmpDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 40));

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 180, 40));

        btnRequestLeave.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRequestLeave.setText("Request Leave");
        btnRequestLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLeaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRequestLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 40));

        btnPayroll.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnPayroll.setText("Payroll");
        btnPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayrollActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/background.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        parentPanel.setBackground(new java.awt.Color(255, 255, 255));
        parentPanel.setLayout(new java.awt.CardLayout());

        EmpDataPanel.setBackground(new java.awt.Color(255, 255, 255));
        EmpDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Full Name:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        lblFullName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFullName.setText("Fullname");
        jPanel3.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 370, 20));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Birthday:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 70, 20));

        lblBirthday.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblBirthday.setText("birthday");
        jPanel3.add(lblBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 160, 20));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Address:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 20));

        lblAddress.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblAddress.setText("address");
        jPanel3.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 610, 20));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setText("Phone:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 20));

        lblPhone.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblPhone.setText("phone_number");
        jPanel3.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, 20));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Status:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, 20));

        lblStatus.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblStatus.setText("status");
        jPanel3.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 140, 20));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setText("Deparment:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 80, 20));

        lblDepartment.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDepartment.setText("department");
        jPanel3.add(lblDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 150, 20));

        lblPosition.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblPosition.setText("postion");
        jPanel3.add(lblPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 150, 20));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Position:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 60, 20));

        lblSupervisor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblSupervisor.setText("supervisor");
        jPanel3.add(lblSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 380, 20));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Supervisor:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 20));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("Basic Information");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 20));

        EmpDataPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 720, 170));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHourlyRate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel4.add(lblHourlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 20));

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 102));
        jLabel22.setText("Salary:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 20));

        lblBasicSalary.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblBasicSalary.setText("salary");
        jPanel4.add(lblBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, 20));

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 102));
        jLabel23.setText("Rate:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Salary Details");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 20));

        EmpDataPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 720, 160));

        lblEmployeeId.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblEmployeeId.setText("employee_id");
        EmpDataPanel.add(lblEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 0, 153));
        jLabel21.setText("Employee ID:");
        EmpDataPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        parentPanel.add(EmpDataPanel, "card2");

        requestLeavePanel.setBackground(new java.awt.Color(255, 255, 255));
        requestLeavePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmployeeId1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblEmployeeId1.setText("employee_id");
        requestLeavePanel.add(lblEmployeeId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 153));
        jLabel24.setText("Leave Type:");
        requestLeavePanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 20));

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 153));
        jLabel25.setText("Employee ID:");
        requestLeavePanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 153));
        jLabel26.setText("Start Date:");
        requestLeavePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 20));
        requestLeavePanel.add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 170, -1));
        requestLeavePanel.add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, -1));

        comboLeaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation Leave", "Sick Leave", "Emergency Leave", "Maternity/Paternity Leave" }));
        requestLeavePanel.add(comboLeaveType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 170, -1));

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 153));
        jLabel27.setText("End Date:");
        requestLeavePanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));

        leaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Employee ID", "Leave Type", "Start Date", "End Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(leaveTable);

        requestLeavePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 720, 310));

        btnRequestLeaveProcess.setText("Request Leave");
        btnRequestLeaveProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLeaveProcessActionPerformed(evt);
            }
        });
        requestLeavePanel.add(btnRequestLeaveProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 160, 30));

        parentPanel.add(requestLeavePanel, "card3");

        payrollPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payrollTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Period ID", "Period Start", "Period End", "Working Hours", "SSS", "PhilHealth", "PAGIBIG", "Witholding Tax", "Rice Subsidy", "Phone Allowance", "Clothing Allowance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        payrollTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payrollTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(payrollTable);
        if (payrollTable.getColumnModel().getColumnCount() > 0) {
            payrollTable.getColumnModel().getColumn(1).setResizable(false);
            payrollTable.getColumnModel().getColumn(2).setResizable(false);
            payrollTable.getColumnModel().getColumn(3).setResizable(false);
            payrollTable.getColumnModel().getColumn(4).setResizable(false);
            payrollTable.getColumnModel().getColumn(5).setResizable(false);
            payrollTable.getColumnModel().getColumn(6).setResizable(false);
            payrollTable.getColumnModel().getColumn(7).setResizable(false);
            payrollTable.getColumnModel().getColumn(8).setResizable(false);
            payrollTable.getColumnModel().getColumn(9).setResizable(false);
        }

        payrollPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 740, 430));

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 153));
        jLabel28.setText("Payroll ID:");
        payrollPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        lblPayrollId.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        payrollPanel.add(lblPayrollId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 310, 20));

        btnGeneratePayslip.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGeneratePayslip.setText("Generate Payslip");
        btnGeneratePayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePayslipActionPerformed(evt);
            }
        });
        payrollPanel.add(btnGeneratePayslip, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 170, -1));

        parentPanel.add(payrollPanel, "card4");

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 760, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpDetailsActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(EmpDataPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_btnEmpDetailsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
    if (choice == JOptionPane.YES_OPTION) {
        dispose(); // Close current dashboard
        new LoginForm().setVisible(true); // Return to login screen
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRequestLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLeaveActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(requestLeavePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        
    }//GEN-LAST:event_btnRequestLeaveActionPerformed

    private void btnRequestLeaveProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLeaveProcessActionPerformed
        // TODO add your handling code here:
        if (loggedInEmployee == null) return;
        
        try {
            String startDateStr = txtStartDate.getText().trim();
            String endDateStr = txtEndDate.getText().trim();
            String leaveType = (String) comboLeaveType.getSelectedItem();
            
            if (startDateStr.isEmpty() || endDateStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Start Date and End Date cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            LocalDate startDate = LocalDate.parse(startDateStr);
            LocalDate endDate = LocalDate.parse(endDateStr);
            
            boolean success = leaveRequestService.submitLeaveRequest(
                loggedInEmployee.getEmployeeId(), leaveType, startDate, endDate
            );
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Leave Request submitted successfully!");
                txtStartDate.setText("");
                txtEndDate.setText("");
                loadLeaveData();
            } else {
                JOptionPane.showMessageDialog(this, "Error submitting leave request.", "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRequestLeaveProcessActionPerformed

    private void btnPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayrollActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(payrollPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        loadPayrollData(); 
    }//GEN-LAST:event_btnPayrollActionPerformed

    private void btnGeneratePayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePayslipActionPerformed
        // TODO add your handling code here:
        String payrollId = lblPayrollId.getText().trim();
        if (payrollId.equals("Click on a payroll record to select") || payrollId.equals("N/A")) {
            JOptionPane.showMessageDialog(this, "Please select a payroll record first.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        reportService.generatePayslip(payrollId);

    }//GEN-LAST:event_btnGeneratePayslipActionPerformed

    private void payrollTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = payrollTable.getSelectedRow();
        if (selectedRow >= 0) {
            Object payrollIdObject = payrollTable.getModel().getValueAt(selectedRow, 0);
            if (payrollIdObject != null) {
                String payrollId = payrollIdObject.toString();
                lblPayrollId.setText(payrollId);
            } else {
                lblPayrollId.setText("N/A");
            }
        }

    }//GEN-LAST:event_payrollTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new EmployeeDB("testuser").setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmpDataPanel;
    private javax.swing.JButton btnEmpDetails;
    private javax.swing.JButton btnGeneratePayslip;
    private javax.swing.JButton btnPayroll;
    private javax.swing.JButton btnRequestLeave;
    private javax.swing.JButton btnRequestLeaveProcess;
    private javax.swing.JComboBox<String> comboLeaveType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBasicSalary;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JLabel lblEmployeeId1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblHourlyRate;
    private javax.swing.JLabel lblPayrollId;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSupervisor;
    private javax.swing.JTable leaveTable;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel payrollPanel;
    private javax.swing.JTable payrollTable;
    private javax.swing.JPanel requestLeavePanel;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
